/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.dictionary.dictionaryapp;

import com.google.gson.JsonObject;
import java.awt.CardLayout;
import java.awt.List;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.speech.EngineException;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;
import org.apache.lucene.document.HalfFloatPoint;

/**
 *
 * @author ADMIN
 */
/**
 * 199 453
 *
 */
public class DictionaryForm extends javax.swing.JFrame {
    
    /*trang search*/
    private final dataProcess dProcessEV;
    private final dataProcess dProcessVE;
    private final TextToSpeech textToSpeech;
    
    /*trang history*/
    private HashMap<String, String> historyWord;
    private DefaultListModel<String> listModel;
    
    /*trang game*/
    private gameProcess gProcess;
    
    public DictionaryForm() throws EngineException {
        listModel = new DefaultListModel<>();
        initComponents();
        dProcessEV = new dataProcess("C:/Users/ADMIN/DictionaryApp/src/resources/com/dictionary/resources/data/EV/eng_vni.index", "C:/Users/ADMIN/DictionaryApp/src/resources/com/dictionary/resources/data/EV/eng_vni.dict");
        dProcessVE = new dataProcess("C:/Users/ADMIN/DictionaryApp/src/resources/com/dictionary/resources/data/VE/vie_en.index", "C:/Users/ADMIN/DictionaryApp/src/resources/com/dictionary/resources/data/VE/vie_en.dict");
        textToSpeech = new TextToSpeech();
        historyWord = new HashMap<>();
        gProcess = new gameProcess("B1", "B2", "C1", "C2");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpHome = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSearch = new javax.swing.JLabel();
        jGame = new javax.swing.JLabel();
        jcloseMenu = new javax.swing.JLabel();
        jHistory = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mainLayout = new javax.swing.JPanel();
        searchPage = new javax.swing.JPanel();
        searchInput = new javax.swing.JPanel();
        jTextIn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        searchOutPut = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextOut = new javax.swing.JTextArea();
        searchHead = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        en2Viet = new javax.swing.JButton();
        vie2En = new javax.swing.JButton();
        speakMaleButton = new javax.swing.JButton();
        gamePage = new javax.swing.JPanel();
        searchHead2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        gameLayout = new javax.swing.JPanel();
        b1Game = new javax.swing.JPanel();
        paragramContainer = new javax.swing.JPanel();
        nextParam = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        paramater = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        ASec = new javax.swing.JRadioButton();
        BSec = new javax.swing.JRadioButton();
        CSec = new javax.swing.JRadioButton();
        DSec = new javax.swing.JRadioButton();
        preQues = new javax.swing.JLabel();
        nextQues = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        quesTionCon = new javax.swing.JTextArea();
        sCore = new javax.swing.JLabel();
        gameMod = new javax.swing.JPanel();
        b1Mode = new javax.swing.JButton();
        c1Mode = new javax.swing.JButton();
        b2Mode = new javax.swing.JButton();
        c2Mode = new javax.swing.JButton();
        historyPage = new javax.swing.JPanel();
        searchHead1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        historyContainer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        historyList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        reloadHis = new javax.swing.JLabel();
        meaningContainer = new javax.swing.JPanel();
        meaningOfWord = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frHome"); // NOI18N
        setSize(new java.awt.Dimension(573, 573));

        jpHome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\DictionaryApp\\src\\resources\\com\\dictionary\\resources\\icon\\bacground2.png")); // NOI18N

        jSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\DictionaryApp\\src\\resources\\com\\dictionary\\resources\\icon\\search.png")); // NOI18N
        jSearch.setText("Tra từ");
        jSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearchMouseClicked(evt);
            }
        });

        jGame.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\DictionaryApp\\src\\resources\\com\\dictionary\\resources\\icon\\game.png")); // NOI18N
        jGame.setText("Trò chơi");
        jGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGameMouseClicked(evt);
            }
        });

        jcloseMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\DictionaryApp\\src\\resources\\com\\dictionary\\resources\\icon\\x.png")); // NOI18N
        jcloseMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcloseMenuMouseClicked(evt);
            }
        });

        jHistory.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\DictionaryApp\\src\\resources\\com\\dictionary\\resources\\icon\\history.png")); // NOI18N
        jHistory.setText("Lịch sử");
        jHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHistoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jcloseMenu))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jGame, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcloseMenu)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jSearch)
                .addGap(65, 65, 65)
                .addComponent(jGame)
                .addGap(66, 66, 66)
                .addComponent(jHistory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\DictionaryApp\\src\\resources\\com\\dictionary\\resources\\icon\\menu.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        mainLayout.setLayout(new java.awt.CardLayout());

        searchInput.setBackground(new java.awt.Color(255, 255, 255));

        jTextIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nhập từ");

        javax.swing.GroupLayout searchInputLayout = new javax.swing.GroupLayout(searchInput);
        searchInput.setLayout(searchInputLayout);
        searchInputLayout.setHorizontalGroup(
            searchInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextIn)
            .addGroup(searchInputLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        searchInputLayout.setVerticalGroup(
            searchInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextIn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchOutPut.setBackground(new java.awt.Color(236, 230, 230));

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextOut.setColumns(20);
        jTextOut.setRows(5);
        jScrollPane1.setViewportView(jTextOut);

        javax.swing.GroupLayout searchOutPutLayout = new javax.swing.GroupLayout(searchOutPut);
        searchOutPut.setLayout(searchOutPutLayout);
        searchOutPutLayout.setHorizontalGroup(
            searchOutPutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        searchOutPutLayout.setVerticalGroup(
            searchOutPutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        searchHead.setBackground(new java.awt.Color(51, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TỪ ĐIỂN ANH VIỆT");

        javax.swing.GroupLayout searchHeadLayout = new javax.swing.GroupLayout(searchHead);
        searchHead.setLayout(searchHeadLayout);
        searchHeadLayout.setHorizontalGroup(
            searchHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        searchHeadLayout.setVerticalGroup(
            searchHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );

        en2Viet.setText("En-Vie");
        en2Viet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                en2VietMouseClicked(evt);
            }
        });

        vie2En.setText("Vie-En");
        vie2En.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vie2EnMouseClicked(evt);
            }
        });

        speakMaleButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\DictionaryApp\\src\\resources\\com\\dictionary\\resources\\icon\\speaker.png")); // NOI18N
        speakMaleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                speakMaleButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout searchPageLayout = new javax.swing.GroupLayout(searchPage);
        searchPage.setLayout(searchPageLayout);
        searchPageLayout.setHorizontalGroup(
            searchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(searchPageLayout.createSequentialGroup()
                .addComponent(searchInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(speakMaleButton)
                .addGap(12, 12, 12))
            .addGroup(searchPageLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(en2Viet)
                .addGap(48, 48, 48)
                .addComponent(vie2En)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(searchOutPut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        searchPageLayout.setVerticalGroup(
            searchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPageLayout.createSequentialGroup()
                .addComponent(searchHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(searchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchPageLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(speakMaleButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vie2En)
                    .addComponent(en2Viet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchOutPut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainLayout.add(searchPage, "searchPage");

        searchHead2.setBackground(new java.awt.Color(51, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TỪ ĐIỂN ANH VIỆT");

        javax.swing.GroupLayout searchHead2Layout = new javax.swing.GroupLayout(searchHead2);
        searchHead2.setLayout(searchHead2Layout);
        searchHead2Layout.setHorizontalGroup(
            searchHead2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        searchHead2Layout.setVerticalGroup(
            searchHead2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );

        gameLayout.setLayout(new java.awt.CardLayout());

        b1Game.setBackground(new java.awt.Color(255, 227, 142));

        paragramContainer.setBackground(new java.awt.Color(102, 255, 255));
        paragramContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        paragramContainer.setPreferredSize(new java.awt.Dimension(680, 203));

        nextParam.setBackground(new java.awt.Color(255, 255, 0));
        nextParam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nextParam.setForeground(new java.awt.Color(0, 0, 0));
        nextParam.setText("Next");
        nextParam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextParamMouseClicked(evt);
            }
        });

        jScrollPane3.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        paramater.setEditable(false);
        paramater.setColumns(20);
        paramater.setLineWrap(true);
        paramater.setRows(5);
        paramater.setWrapStyleWord(true);
        paramater.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(paramater);

        javax.swing.GroupLayout paragramContainerLayout = new javax.swing.GroupLayout(paragramContainer);
        paragramContainer.setLayout(paragramContainerLayout);
        paragramContainerLayout.setHorizontalGroup(
            paragramContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paragramContainerLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        paragramContainerLayout.setVerticalGroup(
            paragramContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nextParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ASec.setBackground(new java.awt.Color(102, 255, 255));
        buttonGroup1.add(ASec);
        ASec.setForeground(new java.awt.Color(0, 0, 0));
        ASec.setText("");

        BSec.setBackground(new java.awt.Color(102, 255, 255));
        buttonGroup1.add(BSec);
        BSec.setForeground(new java.awt.Color(0, 0, 0));
        BSec.setText("");

        CSec.setBackground(new java.awt.Color(102, 255, 255));
        buttonGroup1.add(CSec);
        CSec.setForeground(new java.awt.Color(0, 0, 0));
        CSec.setText("");

        DSec.setBackground(new java.awt.Color(102, 255, 255));
        buttonGroup1.add(DSec);
        DSec.setForeground(new java.awt.Color(0, 0, 0));
        DSec.setText("");

        preQues.setBackground(new java.awt.Color(255, 255, 255));
        preQues.setForeground(new java.awt.Color(0, 0, 0));
        preQues.setText("PreQues");
        preQues.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preQuesMouseClicked(evt);
            }
        });

        nextQues.setBackground(new java.awt.Color(0, 255, 0));
        nextQues.setForeground(new java.awt.Color(0, 0, 0));
        nextQues.setText("NextQues");
        nextQues.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextQuesMouseClicked(evt);
            }
        });

        jScrollPane5.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        quesTionCon.setEditable(false);
        quesTionCon.setColumns(20);
        quesTionCon.setLineWrap(true);
        quesTionCon.setRows(5);
        quesTionCon.setWrapStyleWord(true);
        jScrollPane5.setViewportView(quesTionCon);

        sCore.setForeground(new java.awt.Color(0, 0, 0));
        sCore.setText("score: " + score);
        sCore.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DSec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CSec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BSec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ASec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sCore, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(preQues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextQues)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sCore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ASec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BSec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(CSec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(DSec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preQues)
                    .addComponent(nextQues))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout b1GameLayout = new javax.swing.GroupLayout(b1Game);
        b1Game.setLayout(b1GameLayout);
        b1GameLayout.setHorizontalGroup(
            b1GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paragramContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        b1GameLayout.setVerticalGroup(
            b1GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(b1GameLayout.createSequentialGroup()
                .addComponent(paragramContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        gameLayout.add(b1Game, "b1Game");

        b1Mode.setBackground(new java.awt.Color(102, 255, 255));
        b1Mode.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        b1Mode.setText("B1");
        b1Mode.setPreferredSize(new java.awt.Dimension(308, 257));
        b1Mode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1ModeMouseClicked(evt);
            }
        });

        c1Mode.setBackground(new java.awt.Color(0, 102, 255));
        c1Mode.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        c1Mode.setText("C1");
        c1Mode.setPreferredSize(new java.awt.Dimension(308, 257));
        c1Mode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1ModeMouseClicked(evt);
            }
        });

        b2Mode.setBackground(new java.awt.Color(51, 204, 255));
        b2Mode.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        b2Mode.setText("B2");
        b2Mode.setPreferredSize(new java.awt.Dimension(308, 257));
        b2Mode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2ModeMouseClicked(evt);
            }
        });

        c2Mode.setBackground(new java.awt.Color(0, 51, 153));
        c2Mode.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        c2Mode.setText("C2");
        c2Mode.setPreferredSize(new java.awt.Dimension(308, 257));
        c2Mode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c2ModeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout gameModLayout = new javax.swing.GroupLayout(gameMod);
        gameMod.setLayout(gameModLayout);
        gameModLayout.setHorizontalGroup(
            gameModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameModLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(gameModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(c1Mode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b1Mode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(gameModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(b2Mode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c2Mode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        gameModLayout.setVerticalGroup(
            gameModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameModLayout.createSequentialGroup()
                .addGroup(gameModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(b2Mode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b1Mode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(gameModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c2Mode, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1Mode, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        gameLayout.add(gameMod, "gameMode");

        javax.swing.GroupLayout gamePageLayout = new javax.swing.GroupLayout(gamePage);
        gamePage.setLayout(gamePageLayout);
        gamePageLayout.setHorizontalGroup(
            gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchHead2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gameLayout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 583, Short.MAX_VALUE)
        );
        gamePageLayout.setVerticalGroup(
            gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePageLayout.createSequentialGroup()
                .addComponent(searchHead2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainLayout.add(gamePage, "gamePage");

        searchHead1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TỪ ĐIỂN ANH VIỆT");

        javax.swing.GroupLayout searchHead1Layout = new javax.swing.GroupLayout(searchHead1);
        searchHead1.setLayout(searchHead1Layout);
        searchHead1Layout.setHorizontalGroup(
            searchHead1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        searchHead1Layout.setVerticalGroup(
            searchHead1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );

        historyList.setBackground(new java.awt.Color(204, 204, 204));
        historyList.setModel(listModel);
        historyList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(historyList);

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Các từ đã tra gần đây");

        reloadHis.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\DictionaryApp\\src\\resources\\com\\dictionary\\resources\\icon\\reload.png")); // NOI18N
        reloadHis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reloadHisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout historyContainerLayout = new javax.swing.GroupLayout(historyContainer);
        historyContainer.setLayout(historyContainerLayout);
        historyContainerLayout.setHorizontalGroup(
            historyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historyContainerLayout.createSequentialGroup()
                .addGroup(historyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(historyContainerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reloadHis, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(historyContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(74, 74, 74))
        );
        historyContainerLayout.setVerticalGroup(
            historyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historyContainerLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(reloadHis)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout meaningContainerLayout = new javax.swing.GroupLayout(meaningContainer);
        meaningContainer.setLayout(meaningContainerLayout);
        meaningContainerLayout.setHorizontalGroup(
            meaningContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(meaningOfWord, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
        meaningContainerLayout.setVerticalGroup(
            meaningContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(meaningOfWord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout historyPageLayout = new javax.swing.GroupLayout(historyPage);
        historyPage.setLayout(historyPageLayout);
        historyPageLayout.setHorizontalGroup(
            historyPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchHead1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(historyPageLayout.createSequentialGroup()
                .addComponent(historyContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meaningContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        historyPageLayout.setVerticalGroup(
            historyPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPageLayout.createSequentialGroup()
                .addComponent(searchHead1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(historyPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(historyContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meaningContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        mainLayout.add(historyPage, "historyPage");

        javax.swing.GroupLayout jpHomeLayout = new javax.swing.GroupLayout(jpHome);
        jpHome.setLayout(jpHomeLayout);
        jpHomeLayout.setHorizontalGroup(
            jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHomeLayout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpHomeLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(541, 541, 541))
                    .addComponent(mainLayout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jpHomeLayout.setVerticalGroup(
            jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHomeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jpMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static boolean isEnglish(String text) {
//        return text.matches("^[/x00-/x7F]+$");
        return text.matches("^[\u0000-\u007F]+$");
    }

    public static boolean isVietnamese(String text) {
        return text.matches("^[/p{InBasicLatin}&&[^a-zA-Z]]+$");
    }

    // bien cho phan game
    int count = 0;
    int MAX = 0;
    String levelType = "";
    String anSwer = "";
    int score = 0;
    
    /**
     * mở thanh menu
     * @param evt 
     */
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        new Thread(() -> {
            try {
                for (int i = 0; i <= 155; i++) {
                    jpMenu.setSize(i, 564);
                    Thread.sleep(2);
                }
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }).start();
    }//GEN-LAST:event_jLabel8MouseClicked

    
    /**
     * đóng thanh menu
     * @param evt 
     */
    private void jcloseMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMenuMouseClicked
        // TODO add your handling code here:
        new Thread(() -> {
            try {
                for (int i = 155; i >= 0; i--) {
                    jpMenu.setSize(i, 564);
                    Thread.sleep(2);
                }
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }).start();
    }//GEN-LAST:event_jcloseMenuMouseClicked
    
    /**
     * hiển htij trang search
     * @param evt 
     */
    private void jSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchMouseClicked
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) mainLayout.getLayout();
        layout.show(mainLayout, "searchPage");
    }//GEN-LAST:event_jSearchMouseClicked

    /**
     * hiển thị trang game
     * @param evt 
     */
    private void jGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGameMouseClicked
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) mainLayout.getLayout();
        layout.show(mainLayout, "gamePage");
        CardLayout layout1 = (CardLayout) gameLayout.getLayout();
        layout1.show(gameLayout, "gameMode");
        count = 0;
        MAX = 0;
        levelType = "";
    }//GEN-LAST:event_jGameMouseClicked

    /**
     * hhieern thị lịch sử
     * @param evt 
     */
    private void jHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHistoryMouseClicked
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) mainLayout.getLayout();
        layout.show(mainLayout, "historyPage");
    }//GEN-LAST:event_jHistoryMouseClicked

    /**
     * dịch anh -việt
     * @param evt 
     */
    private void en2VietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_en2VietMouseClicked
        // TODO add your handling code here:
        String word = jTextIn.getText().trim();
        if (!word.isEmpty()) {
            String out = dProcessEV.getMeaning(word);
            if (out != null) {
                jTextOut.setText(out);
                if (listModel.size() > 9) {
                    historyWord.remove(listModel.getElementAt(9));
                    listModel.remove(9);
                }
                if (!historyWord.containsKey(word)) {
                    historyWord.put(word, out);
                    listModel.addElement(word);
                } 
            } else {
                try {
                    jTextOut.setText(APIprocess.ggTranslateAPI(word, "vi"));
                } catch (Exception ex) {
                    Logger.getLogger(DictionaryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(DictionaryForm.this, "Please enter a word to search.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_en2VietMouseClicked

    /**
     * dịch việt anh
     * @param evt 
     */
    private void vie2EnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vie2EnMouseClicked
        // TODO add your handling code here:
        String word = jTextIn.getText().trim();
        if (!word.isEmpty()) {
            String out = dProcessVE.getMeaning(word);
            if (out != null) {
                jTextOut.setText(out);
            } else {
                try {
                    jTextOut.setText(APIprocess.ggTranslateAPI(word, "en"));
                } catch (Exception ex) {
                    Logger.getLogger(DictionaryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(DictionaryForm.this, "Please enter a word to search.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_vie2EnMouseClicked

    /**
     * phát âm
     * @param evt 
     */
    private void speakMaleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_speakMaleButtonMouseClicked
        // TODO add your handling code here:
        String text = jTextIn.getText().trim();
        if (!text.isEmpty()) {
            if (isEnglish(text)) {
                textToSpeech.speak(text);
            } else {
                try {
                    APIprocess.TextToSpeechVI(text);
                } catch (IOException | ExecutionException | InterruptedException | JavaLayerException ex) {
                    Logger.getLogger(DictionaryForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(DictionaryForm.this, "Please enter a word to speak.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_speakMaleButtonMouseClicked

    private void reloadHisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadHisMouseClicked
        // TODO add your handling code here:
        historyList.setModel(listModel);
    }//GEN-LAST:event_reloadHisMouseClicked

    private void historyListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyListMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            int index = historyList.locationToIndex(evt.getPoint());
            String word = listModel.elementAt(index);
            meaningOfWord.setText(historyWord.get(word));
        }
    }//GEN-LAST:event_historyListMouseClicked
    
    /*game code*/
    
    
    /**
     * set context for paramerter
     * @param levelNum
     * @param level 
     */
    private void setParameter(int levelNum, String level) {
        if (level.equals("b1")) {
            String params = gProcess.getPaRamSB1().get(levelNum);
            paramater.setText(params);
        } else if (level.equals("b2")) {
            String params = gProcess.getPaRamSB2().get(levelNum);
            paramater.setText(params);
        } else if (level.equals("c1")) {
            String params = gProcess.getPaRamSC1().get(levelNum);
            paramater.setText(params);
        } else {
            String params = gProcess.getPaRamSC2().get(levelNum);
            paramater.setText(params);
        }
    }
    
    private void setQuAndA(int levelNum, int indexOfQues, String level) {
        if (level.equals("b1")) {
            String quesTion = gProcess.getQuAandAswB1().get(levelNum).get(indexOfQues).get("text").getAsString();
            String aSelect = gProcess.getQuAandAswB1().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("a").getAsJsonObject().get("text").getAsString();
            String bSelect = gProcess.getQuAandAswB1().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("b").getAsJsonObject().get("text").getAsString();
            String cSelect = gProcess.getQuAandAswB1().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("c").getAsJsonObject().get("text").getAsString();
            String dSelect = gProcess.getQuAandAswB1().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("d").getAsJsonObject().get("text").getAsString();
            anSwer = gProcess.getQuAandAswB1().get(levelNum).get(indexOfQues).get("answer").getAsString();
            
            quesTionCon.setText(quesTion);
            ASec.setText(aSelect);
            BSec.setText(bSelect);
            CSec.setText(cSelect);
            DSec.setText(dSelect);
            
        } else if (level.equals("b2")) {
            String quesTion = gProcess.getQuAandAswB2().get(levelNum).get(indexOfQues).get("text").getAsString();
            String aSelect = gProcess.getQuAandAswB2().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("a").getAsJsonObject().get("text").getAsString();
            String bSelect = gProcess.getQuAandAswB2().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("b").getAsJsonObject().get("text").getAsString();
            String cSelect = gProcess.getQuAandAswB2().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("c").getAsJsonObject().get("text").getAsString();
            String dSelect = gProcess.getQuAandAswB2().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("d").getAsJsonObject().get("text").getAsString();
            anSwer = gProcess.getQuAandAswB2().get(levelNum).get(indexOfQues).get("answer").getAsString();
            
            quesTionCon.setText(quesTion);
            ASec.setText(aSelect);
            BSec.setText(bSelect);
            CSec.setText(cSelect);
            DSec.setText(dSelect);
        } else if (level.equals("c1")) {
            String quesTion = gProcess.getQuAandAswC1().get(levelNum).get(indexOfQues).get("text").getAsString();
            String aSelect = gProcess.getQuAandAswC1().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("a").getAsJsonObject().get("text").getAsString();
            String bSelect = gProcess.getQuAandAswC1().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("b").getAsJsonObject().get("text").getAsString();
            String cSelect = gProcess.getQuAandAswC1().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("c").getAsJsonObject().get("text").getAsString();
            String dSelect = gProcess.getQuAandAswC1().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("d").getAsJsonObject().get("text").getAsString();
            anSwer = gProcess.getQuAandAswC1().get(levelNum).get(indexOfQues).get("answer").getAsString();
            
            quesTionCon.setText(quesTion);
            ASec.setText(aSelect);
            BSec.setText(bSelect);
            CSec.setText(cSelect);
            DSec.setText(dSelect);
        } else {
            String quesTion = gProcess.getQuAandAswC2().get(levelNum).get(indexOfQues).get("text").getAsString();
            String aSelect = gProcess.getQuAandAswC2().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("a").getAsJsonObject().get("text").getAsString();
            String bSelect = gProcess.getQuAandAswC2().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("b").getAsJsonObject().get("text").getAsString();
            String cSelect = gProcess.getQuAandAswC2().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("c").getAsJsonObject().get("text").getAsString();
            String dSelect = gProcess.getQuAandAswC2().get(levelNum).get(indexOfQues).get("options").getAsJsonObject().get("d").getAsJsonObject().get("text").getAsString();
            anSwer = gProcess.getQuAandAswC2().get(levelNum).get(indexOfQues).get("answer").getAsString();
            
            quesTionCon.setText(quesTion);
            ASec.setText(aSelect);
            BSec.setText(bSelect);
            CSec.setText(cSelect);
            DSec.setText(dSelect);
        }
    }
    
    private String checkAswer() {
        if (ASec.isSelected()) {
            return "a";
        } else if (BSec.isSelected()) {
            return "b";
        } else if (CSec.isSelected()) {
            return "c";
        } else if (DSec.isSelected()) {
            return "d";
        }
        return "f";
    }
    
    /**
     * mode play
     * @param evt 
     */
    int countQues = 0;
    int numOfQues = 0;
    private void b1ModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1ModeMouseClicked
        // TODO add your handling code here:
        countQues = 0;
        count = 0;
        MAX = 28;
        levelType = "b1";
        score = 0;
        CardLayout layout = (CardLayout) gameLayout.getLayout();
        layout.show(gameLayout, "b1Game");
        setParameter(count, levelType);
        setQuAndA(count, 0, levelType);
        numOfQues = gProcess.getQuAandAswB1().get(count).size();
    }//GEN-LAST:event_b1ModeMouseClicked
    
    private void b2ModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2ModeMouseClicked
        // TODO add your handling code here:
        countQues = 0;
        count = 0;
        MAX = 58;
        levelType = "b2";
        score = 0;
        CardLayout layout = (CardLayout) gameLayout.getLayout();
        layout.show(gameLayout, "b1Game");
        setParameter(count, levelType);
        setQuAndA(count, 0, levelType);
        numOfQues = gProcess.getQuAandAswB2().get(count).size();
    }//GEN-LAST:event_b2ModeMouseClicked

    private void c1ModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1ModeMouseClicked
        // TODO add your handling code here:
        countQues = 0;
        count = 0;
        MAX = 25;
        levelType = "c1";
        score = 0;
        CardLayout layout = (CardLayout) gameLayout.getLayout();
        layout.show(gameLayout, "b1Game");
        setParameter(count, levelType);
        setQuAndA(count, 0, levelType);
        numOfQues = gProcess.getQuAandAswC1().get(count).size();
    }//GEN-LAST:event_c1ModeMouseClicked

    private void c2ModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2ModeMouseClicked
        // TODO add your handling code here:
        countQues = 0;
        count = 0;
        MAX = 9;
        levelType = "c2";
        score = 0;
        CardLayout layout = (CardLayout) gameLayout.getLayout();
        layout.show(gameLayout, "b1Game");
        setParameter(count, levelType);
        setQuAndA(count, 0, levelType);
        numOfQues = gProcess.getQuAandAswC2().get(count).size();
    }//GEN-LAST:event_c2ModeMouseClicked

    private void nextParamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextParamMouseClicked
        // TODO add your handling code here:
        if (countQues < numOfQues) {
            JOptionPane.showMessageDialog(DictionaryForm.this, "Please complete all the questions.");
        } else {
            countQues = 0;
            count++;
            if (count < MAX) {
                if (levelType.equals("b1")) {
                    numOfQues = gProcess.getQuAandAswB1().get(count).size();
                    setParameter(count, levelType);
                    setQuAndA(count, countQues, levelType);
                } else if (levelType.equals("b2")) {
                    numOfQues = gProcess.getQuAandAswB2().get(count).size();
                    setParameter(count, levelType);
                    setQuAndA(count, countQues, levelType);
                } else if (levelType.equals("c1")) {
                    numOfQues = gProcess.getQuAandAswC1().get(count).size();
                    setParameter(count, levelType);
                    setQuAndA(count, countQues, levelType);
                } else {
                    numOfQues = gProcess.getQuAandAswC2().get(count).size();
                    setParameter(count, levelType);
                    setQuAndA(count, countQues, levelType);
                }
            } else {
                JOptionPane.showMessageDialog(DictionaryForm.this, "", "CONGRATULATION", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("C:/Users/ADMIN/DictionaryApp/src/resources/com/dictionary/resources/icon/congratulation.png"));
            }
        }
    }//GEN-LAST:event_nextParamMouseClicked

    private void nextQuesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextQuesMouseClicked
        // TODO add your handling code here:
        if (checkAswer().equals("f")) {
            JOptionPane.showMessageDialog(DictionaryForm.this, "You haven't selected an answer yet. Please select");
        } else {
            if (checkAswer().equals(anSwer)) {
                score += 10;
            }
            countQues++;
            if (countQues < numOfQues && countQues >= 0) {

                setQuAndA(count, countQues, levelType);
            } else {
                JOptionPane.showMessageDialog(DictionaryForm.this, "End of questions");
            }
        }
        sCore.setText("score: " + score);
    }//GEN-LAST:event_nextQuesMouseClicked

    private void preQuesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preQuesMouseClicked
        // TODO add your handling code here:
        countQues--;
        if (countQues >= 0 && countQues < numOfQues) {
            setQuAndA(count, countQues, levelType);
            if (checkAswer().equals(anSwer)) {
                score -= 10;
            }
        } else {
            JOptionPane.showMessageDialog(DictionaryForm.this, "End of questions");
        }
    }//GEN-LAST:event_preQuesMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new DictionaryForm().setVisible(true);
            } catch (EngineException ex) {
                Logger.getLogger(DictionaryForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ASec;
    private javax.swing.JRadioButton BSec;
    private javax.swing.JRadioButton CSec;
    private javax.swing.JRadioButton DSec;
    private javax.swing.JPanel b1Game;
    private javax.swing.JButton b1Mode;
    private javax.swing.JButton b2Mode;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton c1Mode;
    private javax.swing.JButton c2Mode;
    private javax.swing.JButton en2Viet;
    private javax.swing.JPanel gameLayout;
    private javax.swing.JPanel gameMod;
    private javax.swing.JPanel gamePage;
    private javax.swing.JPanel historyContainer;
    private javax.swing.JList<String> historyList;
    private javax.swing.JPanel historyPage;
    private javax.swing.JLabel jGame;
    private javax.swing.JLabel jHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel jSearch;
    private javax.swing.JTextField jTextIn;
    private javax.swing.JTextArea jTextOut;
    private javax.swing.JLabel jcloseMenu;
    private javax.swing.JPanel jpHome;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel mainLayout;
    private javax.swing.JPanel meaningContainer;
    private java.awt.TextArea meaningOfWord;
    private javax.swing.JButton nextParam;
    private javax.swing.JLabel nextQues;
    private javax.swing.JPanel paragramContainer;
    private javax.swing.JTextArea paramater;
    private javax.swing.JLabel preQues;
    private javax.swing.JTextArea quesTionCon;
    private javax.swing.JLabel reloadHis;
    private javax.swing.JLabel sCore;
    private javax.swing.JPanel searchHead;
    private javax.swing.JPanel searchHead1;
    private javax.swing.JPanel searchHead2;
    private javax.swing.JPanel searchInput;
    private javax.swing.JPanel searchOutPut;
    private javax.swing.JPanel searchPage;
    private javax.swing.JButton speakMaleButton;
    private javax.swing.JButton vie2En;
    // End of variables declaration//GEN-END:variables
}
